### PR TITLE
gitter.py: Reply an empty reply if the message was from the bot itself

### PR DESCRIPTION
**Pull request by meetmangukiya**
Fixes https://github.com/errbotio/err-backend-gitter/issues/12

### CODE REVIEW

**Comment by meetmangukiya** [comment]
I have tested this locally with message like `!echo !echo what is this`, it didn't echo second time, it does with existing backend :D 

This might not be the prettiest way to do this, but it works, am open to suggestions though, thanks!

**Comment by meetmangukiya** [comment]
@gbin please review

**Comment by gbin** [comment]
Sorry but no this is not the place at all to put this patch on. If the identities are setup correctly, core.py should already filter out the messages from self. https://github.com/errbotio/errbot/blob/master/errbot/core.py#L222

This backend identities don't compare correctly or something.

**Comment by meetmangukiya** [comment]
Ok :+1: thanks for the link. Will update accordingly :)

**Pull request closed without merging**
